### ISSUE TITLE
How to get Marker objects out of Marker components

### ISSUE THREAD

**Issue by gerritvanaaken** [xon52/v3-gmaps#16]
Hi there, the new v3 Version works mostly fine here, thanks!

To get the "native" MarkerClusterer Library working, I still need help:

- events for "mounted" and "unmounted" are missing on the gmapsMarker Component
- on those events, the payload should be the original GoogleMaps Marker object

With these 2 changes, I could add and remove Markers on the markerClustererPlus Library.

**Comment by xon52** [comment]
Great idea. Maybe all events should be firing the Google component. Would be more extensible and much simpler from my side 😅 
Maybe a V1 consideration as it would be very breaking!!

This has been implemented in `v0.1.15` through #15.
The Stackblitz demo is bugged because of Vue Router, but if you want to see it in action and outputting to the console, you can check out the [codesandbox version](https://codesandbox.io/s/v3-gmaps-demo-1flr5). Just move over to `Markers 2`, click on the map somewhere to mount a new pin (and click on the added pin to unmount) and open the console to see the object being returned.

LMK if you have any questions.

**Comment by gerritvanaaken** [comment]
Wow, that was fast. I will look into 0.1.15 very soon and see if it fits my use case!

**Comment by gerritvanaaken** [comment]
Works like a charm, thank you very much. Marker Clusters are working now, using MarkerClustererPlus.

**Comment by xon52** [comment]
Glad I could help. I'm curious to see how you use it? Could share a snippet or something? Might add it to the docs.

**Comment by gerritvanaaken** [comment]
Sure, here are some selected lines from the component. (This uses the "old" MarkerClustererPlus which will be deprecated soonish. The brand-new "MarkerClusterer" yet has a lot of features and documentation missing, so we don’t use it at the moment. See it in action here: https://scouter.nicht.live/app/nuernberg

```````
<template>
...
<gmaps-map
  :options="mapmodel"
  @mounted="initMap">

  <gmaps-marker 
    v-for="station in filteredStations" // filteredStation is reactive and changes all the time
    :key="station.id"
    :position="{ lat: station.coordinates[1], lng: station.coordinates[0] }"
    @mounted="addMarker"
    @unmounted="removeMarker"
  />

</gmaps-map>
...
</template>

<script setup>
import {ref, toRaw, computed, inject, onMounted, onUpdated} from 'vue';
import {gmapsMap, gmapsMarker, gmapsPolygon} from 'v3-gmaps';
import MarkerClusterer from '@googlemaps/markerclustererplus';
...

const globalmap = ref(null);
let markerClusterer = null; // no reactivity, please!

const addMarker = (marker) => {
	markerClusterer.addMarker(marker);
};
const removeMarker = (marker) => {
	markerClusterer.removeMarker(marker);
};

const initMap = (map) => {
	globalmap.value = map;
	
	// init clusterer
	markerClusterer = new MarkerClusterer(toRaw(map), [], { // kill map reactivity for clusterer, it will crash otherwise
		gridSize: 20,
		maxZoom: 13,
		styles: [
			MarkerClusterer.withDefaultStyle({
				width: 30,
				height: 30,
				textColor: '#fff',
				textSize: 12,
				fontFamily: 'Castledown',
				fontWeight: 300
			})
		]
	});
};

```````

**Comment by xon52** [comment]
Amazing. Thanks for that! I might try include as an example sometime when I next get the itch or prompt to update this!!
